server:
  port: 8888
spring:
  cloud:
    gateway:
      - id: user-web
        uri: lb://USER-WEB
        predicates:
          - Path=/user/**,/res/**
      - id: post-web
        uri: lb://POST-WEB
        predicates:
          - Path=/post/**
      - id: friend-web
        uri: lb://FRIEND-WEB
        predicates:
          - Path=/friend/**,/friendsapply/**
  application:
    name: redblog-gateway