server:
  port: 8085
spring:
  application:
    name: post-web
  datasource:
    password: Hzz19990609!
    username: root
    url: jdbc:mysql://localhost:3306/redBlog
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.redBlog.entity